version: '3'
services:
  app:
    build: ./src/paper/
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: udp
        mode: host
    restart: unless-stopped
  proxy:
    build: ./src/geyser/
    links:
      - app
    ports:
      - target: 19132
        published: 19132
        protocol: tcp
        mode: host
      - target: 19132
        published: 19132
        protocol: udp
        mode: host
    restart: unless-stopped